version: 1
formatters:
  std:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: std
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: std
    filename: "data/logs/pipeline_master.log"
loggers:
  CS4Downloader:
    level: INFO
    handlers: [console, file]
    propagate: false
  CS4Parser:
    level: INFO
    handlers: [console, file]
    propagate: false
  CS4Generator:
    level: INFO
    handlers: [console, file]
    propagate: false
  CS4Evaluator:
    level: INFO
    handlers: [console, file]
    propagate: false
  CS4Pipeline:
    level: INFO
    handlers: [console, file]
    propagate: false
root:
  level: WARNING
  handlers: [console]
